CREATE DATABASE QL_IDNAME

CREATE TABLE THONGTIN(
	ID INT NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO THONGTIN(ID,NAME) VALUES (1,'MINH NHAT');
INSERT INTO THONGTIN(ID,NAME) VALUES (2,'MINH MINH');
INSERT INTO THONGTIN(ID,NAME) VALUES (3,'NHAT NHAT');
INSERT INTO THONGTIN(ID,NAME) VALUES (4,'NHAT MINH');
INSERT INTO THONGTIN(ID,NAME) VALUES (5,'NHAT MOI');

SELECT * FROM THONGTIN
